- name: creating ec2 imstances and creating route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0f34bb41316585429
    ami_id: ami-0220d79f3f480ecf5
    region: us-east-1
    instance_type: t3.micro
    env: dev
    instances:
     - mongodb
     - catalogue
     - frontend
     - redis
     - users
    action: create
    domain_name: devopswiththota.online

  tasks:
  - name: creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}-{{ env }}"      #mongodb-dev
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      tags:
        Project: roboshop
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    when: action == "create"
    register: ec2_output

  - name: reading the ec2 output data
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"   

  - name: creating r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item}}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true  
      loop: "{{ ec2_output.results }}" 
      when: action == "create"

  - name: creating r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" #roboshop-env.devopswiththota.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true  
      loop: "{{ ec2_output.results }}" 
      when:
       -item.item == "frontend"
       action == "create"

      