- name: creating ec2 imstances and creating route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0f34bb41316585429
    ami_id: ami-0220d79f3f480ecf5
    region: us-east-1
    instance_type: t3.micro
    env: dev
    instances:
     - mongodb
     - catalogue
     - frontend
     - redis
     - users
    state: create
  tasks:
  - name: creating ec2 instances
    ansible.aws.ec2_instance:
      name: "{{ item }}-{{ env }}"      #mongodb-dev
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      tags:
        Project: roboshop
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
      loop: {{ instances }}
      when: state == create
      register: ec2_output

  - name: reading the ec2 output data
    ansible.builtin.debug:
      msg: "{{ register }}"      
      