- name: configuring cart service on ec2 instance
  hosts: cart
  become: yes
  tasks:
  - name: enabling the nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: creating system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      comment: "roboshop system user"
      home: /app
      system: yes
  - name: deleting /app directory
    ansible.builtin.file:
      path: /app
      state: absent
  - name: deleting /app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Verify /app exists
    ansible.builtin.command: ls -ld /app
    register: app_check
  - name: print the message for temporary
    ansible.builtin.debug:
      msg: "{{ app_check }}"
  - name: deleting cart from /tmp
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent
  - name: downloading from s3
    ansible.builtin.get.url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      path: /tmp/cart.zip
  - name: unzipping the file from /tmp to /app
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  - name: installing dependencies
    community.general.npm:
      name: npm
      path: /app
  - name: configuring cart.service file
    ansible.builtin.template:
      src: cart.service
      dest: /etc/systemd/system/cart.service
  - name: starting and enabling cart
    ansible.builtin.service:
      name: cart
      state: started
      enable: yes